### ISSUE TITLE
Make new hacking tool

### ISSUE THREAD

**Issue by GH05T-HUNTER5** [AgeOfMarcus/cprCartSurfer#1]
Let's both collaborate and make a new hacking tool invite me

Id : GH05T-HUNTER5

**Comment by AgeOfMarcus** [comment]
Brother this isn't a hacking tool. 

Also what do you mean invite you? To what? Where? What platform? You gave me a fucking ID, what am I supposed to do with it?

**Comment by GH05T-HUNTER5** [comment]
> 
F U B

**Comment by AgeOfMarcus** [comment]
You're not a hacker either bro chill
